package com.stage.pfe.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * cinema generated by hbm2java
 */
public class Cinema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcinema;
	private String nomcinema;
	private String adresse;
	
	private Set<Salle> salles = new HashSet<Salle>(0);
	
	
	
	public Cinema() {
	}

	public Cinema ( String nomcinema, String adresse) {
	
		this.nomcinema = nomcinema;
		this.adresse = adresse;
		
	}

	public Integer getIdcinema() {
		return idcinema;
	}

	public void setIdcinema(Integer idcinema) {
		this.idcinema = idcinema;
	}

	public String getNomcinema() {
		return nomcinema;
	}

	public void setNomcinema(String nomcinema) {
		this.nomcinema = nomcinema;
	}

	public String getAdresse() {
		return adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	

	@Override
	public String toString() {
		return "Cinema [idcinema=" + idcinema + ", nomcinema=" + nomcinema
				+ ", adresse=" + adresse + "]";
	}

	public Set<Salle> getSalles() {
		return salles;
	}

	public void setSalles(Set<Salle> salles) {
		this.salles = salles;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adresse == null) ? 0 : adresse.hashCode());
		result = prime * result
				+ ((idcinema == null) ? 0 : idcinema.hashCode());
		result = prime * result
				+ ((nomcinema == null) ? 0 : nomcinema.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cinema other = (Cinema) obj;
		if (adresse == null) {
			if (other.adresse != null)
				return false;
		} else if (!adresse.equals(other.adresse))
			return false;
		if (idcinema == null) {
			if (other.idcinema != null)
				return false;
		} else if (!idcinema.equals(other.idcinema))
			return false;
		if (nomcinema == null) {
			if (other.nomcinema != null)
				return false;
		} else if (!nomcinema.equals(other.nomcinema))
			return false;
		return true;
	}
}
	
	
	
	
	
	
	
	
	