package com.stage.pfe.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * film generated by hbm2java
 */
public class Film implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idfilm;
	private String annee;
	private String nom_realisateur;
	private String titre;
	private Set<Seance> seances = new HashSet<Seance>(0);

	
	
	
	
	public Set<Seance> getSeances() {
		return seances;
	}

	public void setSeances(Set<Seance> seances) {
		this.seances = seances;
	}

	public Film() {
	}

	public Film ( String annee, String nom_realisateur, String titre) {
		
		this.annee = annee;
		this.nom_realisateur = nom_realisateur;
		this.titre = titre;
	}
	
	
	

	public String getTitre() {
		return titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getNom_realisateur() {
		return nom_realisateur;
	}

	public void setNom_realisateur(String nom_realisateur) {
		this.nom_realisateur = nom_realisateur;
	}

	public String getAnnee() {
		return annee;
	}

	public void setAnnee(String annee) {
		this.annee = annee;
	}

	public Integer getIdfilm() {
		return idfilm;
	}

	public void setIdfilm(Integer idfilm) {
		this.idfilm = idfilm;
	}



	@Override
	public String toString() {
		return "Film [idfilm=" + idfilm + ", annee=" + annee
				+ ", nom_realisateur=" + nom_realisateur + ", titre=" + titre
				+ "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((annee == null) ? 0 : annee.hashCode());
		result = prime * result + ((idfilm == null) ? 0 : idfilm.hashCode());
		result = prime * result
				+ ((nom_realisateur == null) ? 0 : nom_realisateur.hashCode());
		result = prime * result + ((titre == null) ? 0 : titre.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Film other = (Film) obj;
		if (annee == null) {
			if (other.annee != null)
				return false;
		} else if (!annee.equals(other.annee))
			return false;
		if (idfilm == null) {
			if (other.idfilm != null)
				return false;
		} else if (!idfilm.equals(other.idfilm))
			return false;
		if (nom_realisateur == null) {
			if (other.nom_realisateur != null)
				return false;
		} else if (!nom_realisateur.equals(other.nom_realisateur))
			return false;
		if (titre == null) {
			if (other.titre != null)
				return false;
		} else if (!titre.equals(other.titre))
			return false;
		return true;
	}
}
	
	
	
	
	
	
	
	
	