package com.stage.pfe.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * salle generated by hbm2java
 */
public class Salle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idsalle;
	private String nomsalle;
	private String capacite;
	private Cinema cinema;
	private Set<Seance> seances = new HashSet<Seance>(0);
	 
	
	
	

	public Cinema getCinema() {
		return cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	public Set<Seance> getSeances() {
		return seances;
	}

	public void setSeances(Set<Seance> seances) {
		this.seances = seances;
	}

	public String getNomsalle() {
		return nomsalle;
	}

	public void setNomsalle(String nomsalle) {
		this.nomsalle = nomsalle;
	}
	
	
	
	public Salle() {
	}

	

	public Salle  (String nomsalle, String capacite) {
		
		this.nomsalle = nomsalle;
		this.capacite = capacite;
	}

	public Integer getIdsalle() {
		return idsalle;
	}

	public void setIdsalle(Integer idsalle) {
		this.idsalle = idsalle;
	}

	

	public String getCapacite() {
		return capacite;
	}

	public void setCapacite(String capacite) {
		this.capacite = capacite;
	}

	

	@Override
	public String toString() {
		return "Salle [idsalle=" + idsalle + ", nomsalle=" + nomsalle
				+ ", capacite=" + capacite + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((capacite == null) ? 0 : capacite.hashCode());
		result = prime * result + ((idsalle == null) ? 0 : idsalle.hashCode());
		result = prime * result
				+ ((nomsalle == null) ? 0 : nomsalle.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Salle other = (Salle) obj;
		if (capacite == null) {
			if (other.capacite != null)
				return false;
		} else if (!capacite.equals(other.capacite))
			return false;
		if (idsalle == null) {
			if (other.idsalle != null)
				return false;
		} else if (!idsalle.equals(other.idsalle))
			return false;
		if (nomsalle == null) {
			if (other.nomsalle != null)
				return false;
		} else if (!nomsalle.equals(other.nomsalle))
			return false;
		return true;
	}
	
	
}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	